### ISSUE TITLE
maxListeners of 0 is unlimited

### ISSUE THREAD

**Issue by omsmith** [nolanlawson/throw-max-listeners-error#1]
> # emitter.setMaxListeners(n)
> 
> By default EventEmitters will print a warning if more than 10 listeners are added for a particular event. This is a useful default which helps finding memory leaks. Obviously not all Emitters should be limited to 10. This function allows that to be increased. **Set to zero for unlimited.**

(emphasis mine)

**Comment by omsmith** [comment]
Cause of failure in https://github.com/pouchdb/pouchdb/pull/4129 (due to https://github.com/request/request/pull/957)

**Comment by nolanlawson** [comment]
fixed by #3
